### ISSUE TITLE
Remove the previous artwork

### ISSUE THREAD

**Issue by aarkkappler** [cvzi/py_itunesart#5]
Hi CVZI is there a switch to remove the previous when I click on the new one ?

**Comment by cvzi** [comment]
It should always replace the previous one. Does it not remove the previous one for you?

**Comment by aarkkappler** [comment]
not it does not 

My Teams : https://teams.microsoft.com/join/tad4sadukd53

**Comment by cvzi** [comment]
I will check why this is happening. Maybe I add a button to remove it. If it is easy to program, it maybe could show the previous album artwork in the Gui.

**Comment by aarkkappler** [comment]
Great :)

**Comment by cvzi** [comment]
This is now possible with the `-r` parameter in the command:
`C:\pathtofile\gui.py -r "%_path%"` instead of `C:\pathtofile\gui.py "%_path%"`
or for album
`C:\pathtofile\gui.py -a -r "%_path%"` instead of `C:\pathtofile\gui.py -a "%_path%"`

See [README](https://github.com/cvzi/py_itunesart#only-cover-from-itunes-single-song)

**Comment by aarkkappler** [comment]
many thanks :)
